# Generated by Django 3.0.8 on 2020-07-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shows',
            field=models.ManyToManyField(related_name='users', through='tracker.UserShowList', to='tracker.Show'),
        ),
    ]
