# Generated by Django 3.0.8 on 2020-07-18 13:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='service',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None),
        ),
    ]
