# Generated by Django 3.0.8 on 2020-07-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200718_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usershowlist',
            options={'ordering': ('date_added',)},
        ),
    ]
